#!/bin/sh

LABELOID="1.3.6.1.4.1.318.1.1.4.4.2.1.4"

cat device \
| while read PDUIP PDUNAME READCOM WRITECOM JUNK
do

  [ -z $READCOM ] && READCOM=default
  if grep "^${READCOM} " snmpassword >/dev/null
  then
    READCOM=`grep "^${READCOM} " snmpassword | sed 's/^[^ ]* \([^ ]*\) .*$/\1/'`
  fi

  snmpwalk -v2c -On -c $READCOM $PDUIP 1.3.6.1.4.1.318.1.1.4.4.2.1.4 \
  | sed -e 's/^.'${LABELOID}'./'${PDUIP}' '${PDUNAME}' OUTLET /' \
        -e 's/ = STRING:/ SERVER/' \
        -e 's/\(".*\) \(.*"\)/\1_\2/g' \
        -e 's/"//g'
done \
| while read PDUIP PDUNAME OUTTAG OUTLET SERVERTAG SERVER JUNK
do
  echo $PDUIP $PDUNAME $OUTTAG $OUTLET $SERVERTAG $SERVER $JUNK >&2
  echo $PDUIP $PDUNAME $OUTLET $SERVER $JUNK
done \
> serveroutlet
